// src/Map.tsx
import './Map.css';

import * as d3 from "d3";
import { tile } from 'd3-tile';
import * as topojson from 'topojson-client';
import { topoJSON } from 'topojson-client';

import { URLs } from './map_utils.ts';

const projection = d3.geoMercator();
const path = d3.geoPath(projection);

const url = URLs["Stamen Toner"];
type TileCoords = { x: number, y: number, z: number, tx: number, ty: number, k: number }

function Map({ width, height }: { width: number, height: number }) {
    Promise.all([
        d3.json('./data/comunas.topo'),
        d3.json('./data/barrios.topo')
    ]).then(([comunas, barrios]: [topoJSON, topoJSON]) => {
        const t = tile()
            .size([600, 600])
            .scale(projection.scale() * 2 * Math.PI)
            .translate(projection([0, 0]));

        const topo = {
            comunas: topojson.feature(comunas, comunas.objects.comunas),
            barrios: topojson.feature(barrios, barrios.objects.barrios),
            mesh: topojson.mesh(comunas, comunas.objects.comunas,
                (a, b) => a === b)
        }
        projection.fitExtent([[0, 0], [600, 600]], topo.comunas)
        t.scale(projection.scale() * 2 * Math.PI)
            .translate(projection([0, 0]))
        const svg = d3.select('#svg');
        svg.selectAll('*').remove();
        svg.append('defs').append('g').attr('id', 'tiles')
            .selectAll('.tile')
            .data(t().map(([x, y, z]: number[],
                _i: number,
                { translate: [tx, ty], scale: k }: { translate: number[], scale: number }
            ) => ({ x, y, z, tx, ty, k })))
            .join('image')
            .attr('class', 'tile')
            .attr('xlink:href', ({ x, y, z }) => url(x, y, z))
            .attr('x', ({ x, tx, k }) => Math.round((x + tx) * k))
            .attr('y', ({ y, ty, k }) => Math.round((y + ty) * k))
            .attr('width', ({ k }) => k)
            .attr('height', ({ k }) => k)

        const cprop = (d: topoJSON) => `comuna${d.properties.ID}`;
        svg.append('g').attr('class', 'comunas')
            .selectAll('.comuna')
            .data(topo.comunas.features, d => d.properties.COMUNAS)
            .join(
                enter => {
                    const g = enter.append('g')
                        .attr('class', 'comuna')
                        .attr('id', (d: topoJSON) => d.properties.COMUNAS)
                        .on("mouseover", function() {
                            svg.selectAll('.comuna')
                                .classed('raised', false)
                            const sel = d3.select(this)
                            sel.raise()
                                .classed('raised', true)
                        })

                    g.append('path').attr('d', path);
                    const clipPath = g.append('clipPath').attr('id', cprop)
                    clipPath.append('path').attr('d', path);

                    const barrios = g.append('g').attr('class', 'barrios')
                    barrios.append('use').attr('xlink:href', '#tiles').attr('clip-path', d => `url(#${cprop(d)})`)
                    barrios.selectAll('.barrio')
                        .data((d: topoJSON) => topo.barrios.features
                            .filter((f: topoJSON) => f.properties.COMUNA === d.properties.COMUNAS),
                            (d: topoJSON) => d.properties.BARRIO)
                        .join('path')
                        .attr('class', 'barrio')
                        .attr('fill', 'transparent')
                        .attr('id', (d: topoJSON) => d.properties.BARRIO)
                        .attr('d', path)
                    return g;
                }
            )
    })
    return (<svg id="svg" className="map" width={width} height={height}></svg>)
}

export default Map;

// src/Map.svelte
<script lang="ts">
 import * as d3  from "d3";
 import {tile} from 'd3-tile';
 import * as topojson from 'topojson-client';
 export let width;
 export let height;

 const access_token ="pk.eyJ1Ijoic2VydWdlbmVyaXMiLCJhIjoiY2w3dzB4aHZyMDh1ZDN2cXRiZ3M2emh5OCJ9.w5ChPmWEjwfdL5Zbglcrmg";
 const tileset="mapbox.mapbox-streets-v8";

 const projection = d3.geoMercator();
 const path = d3.geoPath(projection);

 let urls = new Set();

 const url = (x, y, z) => {
     const ret = `./tiles/${"abc"[Math.abs(x + y) % 3]}.tiles.mapbox.com/v4/${tileset}/${z}/${x}/${y}${devicePixelRatio > 1 ? "@2x" : ""}.png?access_token=${access_token}`;
     urls.add(ret)
     let  s = '';
     for (let e of urls) {
         s+=e + '\n'
     }
     console.error(s)
     return ret;
 }

 Promise.all([
     d3.json('./data/comunas.topo'),
     d3.json('./data/barrios.topo')
 ]).then(([comunas, barrios]) => {
     console.error(comunas, barrios)
     const t = tile()
         .size([600, 600])
         .scale(projection.scale() * 2 * Math.PI)
         .translate(projection([0, 0]));

     const topo = {
         comunas: topojson.feature(comunas, comunas.objects.comunas),
         barrios: topojson.feature(barrios, barrios.objects.barrios),
         mesh: topojson.mesh(comunas, comunas.objects.comunas,
                             (a,b) => a===b)
     }
     projection.fitExtent([[0,0], [600,600]], topo.comunas )
     t.scale(projection.scale() * 2 * Math.PI)
               .translate(projection([0, 0]))
     const svg = d3.select('#svg');

     svg
                   .selectAll('.comuna')
                   .data(topo.comunas.features, d => d.properties.COMUNAS)
                   .join(
                       enter => {
                           const g = enter.append('g')
                                          .attr('class', 'comuna')
                                          .attr('id', d => d.properties.COMUNAS)
                                          .on("mouseover", function() {
                                              svg.selectAll('.comuna')
                                              .classed('raised', false)
                                              const sel = d3.select(this)
                                              sel.raise()
                                              .classed('raised', true)
                                          })

                           g.append('path')
                                          .attr('d', path);

                           g.append('g')
                            .attr('class', 'barrios')
                            .selectAll('.barrio')
                            .data(d => topo.barrios.features.filter(function (f) {
                                console.error(this, d)
                                return f.properties.COMUNA === d.properties.COMUNAS
                            }), d => d.properties.BARRIO)
                            .join('path')
                            .attr('class', 'barrio')
                            .attr('id', d => d.properties.BARRIO)
                            .attr('d', path)
                       }

                   )

 }) 
</script>

<svg id="svg" class="map" {width} {height}></svg>

<style>
 .map {
     transition: all 200ms;
 }
 .map.selection {
     transform: rotateX(45deg);
 }
 :global(path) {
     fill: white;
     stroke: black;
     transition: all 200ms;
     transform-origin: center;
     transform-box: fill-box;
 }

 :global(.raised .barrio) {
     opacity: 1;
 }
 :global(.barrio) {
     stroke: yellow;
     opacity: 0;
     transition: all 500ms;
 }
 .barrios {
     display: none;
 }
 .contour {

 }
 .contour path {
     stroke: red;
     stroke-width: 50px;
     stroke-linejoin: round;
     fill: black;
 }

 :global(.comuna) {
     transform-box: fill-box;
     transform-origin: center;
 }
 .selected {
     fill: darkred!important;
     transform: scale(4);
     transform-origin: center;
     transform-box: fill-box;
 }

 :global(.comuna:hover) {
     transform: scale(1.5) ;
     z-index: 99;
 }
 :global(.comuna:hover path) {
     fill: darkgreen;
 }

 .cluster:hover .barrios {
     display: block;
 }
 .selected path:hover {
     transform: none!important;
 }

</style>
